//! Card SVG asset management
//!
//! This module handles loading and caching of playing card SVG images
//! as PDF XObjects for efficient reuse in rendering.

use printpdf::{PdfDocument, PdfWarnMsg, Pt, Px, Svg, XObjectId, XObjectTransform};
use std::collections::{HashMap, HashSet};

use crate::model::{Rank, Suit, RANKS_DISPLAY_ORDER, SUITS_DISPLAY_ORDER};

/// Card dimensions based on actual SVG assets
/// SVG viewport: 167.0869141pt × 242.6669922pt
/// Converted to mm: 58.94mm × 85.61mm (1pt = 25.4/72 mm)
pub const CARD_WIDTH_MM: f32 = 58.94;
pub const CARD_HEIGHT_MM: f32 = 85.61;

/// DPI used for SVG parsing (matches printpdf default)
const SVG_DPI: f32 = 300.0;

/// Which rendition of a card to draw.
///
/// The court-card illustrations are enormous -- the twelve J/Q/K assets are
/// ~98% of a declarer's plan PDF -- but those layouts hardly ever show a whole
/// court card. Reduced variants (generated by `tools/make_card_variants.py`)
/// cover the parts that are actually visible, and only the rare fully-exposed
/// card pays for the full illustration.
#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum CardFace {
    /// The complete card. Needed only when nothing covers it.
    Full,
    /// The top of the card, for a card covered in a dummy stack.
    Band,
    /// Card, border and top-left index only, for a card covered in the fan.
    Corner,
}

impl CardFace {
    /// Spot cards have no reduced variants -- their art is already tiny, and
    /// below the index their left edge is blank, so the fan and dummy show
    /// exactly the same thing whichever rendition is used.
    pub fn resolve(self, rank: Rank) -> CardFace {
        if matches!(rank, Rank::Jack | Rank::Queen | Rank::King) {
            self
        } else {
            CardFace::Full
        }
    }
}

/// Manages SVG card images as XObjects for PDF rendering
pub struct CardAssets {
    cards: HashMap<(Suit, Rank, CardFace), XObjectId>,
}

impl CardAssets {
    /// Load all 52 full-size card SVGs and register them as XObjects
    ///
    /// SVGs are embedded at compile time from assets/cards/
    pub fn load(doc: &mut PdfDocument) -> Result<Self, CardLoadError> {
        let mut needed = HashSet::new();
        for suit in SUITS_DISPLAY_ORDER {
            for rank in RANKS_DISPLAY_ORDER {
                needed.insert((suit, rank, CardFace::Full));
            }
        }
        Self::load_faces(doc, &needed)
    }

    /// Register only the card renditions a document actually draws.
    ///
    /// Every XObject added to the document is written to the file whether or
    /// not any page invokes it, so registering all 52 full cards costs ~3.9MB
    /// even when the layout shows only slivers of them.
    pub fn load_faces(
        doc: &mut PdfDocument,
        needed: &HashSet<(Suit, Rank, CardFace)>,
    ) -> Result<Self, CardLoadError> {
        let mut cards = HashMap::new();
        let mut warnings: Vec<PdfWarnMsg> = Vec::new();

        // Sorted, because every XObject registered here lands in the document in
        // iteration order and a HashSet's is seeded differently per set. Left
        // unsorted, the same boards produce a different byte stream on every
        // run: identical content, different object numbering. That rewrote 184
        // committed PDFs on each Baker Bridge rebuild (issue #11).
        let mut needed: Vec<(Suit, Rank, CardFace)> = needed.iter().copied().collect();
        needed.sort_unstable();

        for (suit, rank, face) in needed {
            let face = face.resolve(rank);
            if cards.contains_key(&(suit, rank, face)) {
                continue;
            }
            let svg_content = match face {
                CardFace::Full => get_card_svg(suit, rank)?,
                CardFace::Band => {
                    court_variants(suit, rank)
                        .ok_or(CardLoadError::MissingCard { suit, rank })?
                        .0
                }
                CardFace::Corner => {
                    court_variants(suit, rank)
                        .ok_or(CardLoadError::MissingCard { suit, rank })?
                        .1
                }
            };
            let xobject = Svg::parse(svg_content, &mut warnings).map_err(|e| {
                CardLoadError::SvgParseError {
                    suit,
                    rank,
                    message: e,
                }
            })?;
            let id = doc.add_xobject(&xobject);
            cards.insert((suit, rank, face), id);
        }

        Ok(Self { cards })
    }

    /// Get the XObjectId for a full-size card
    pub fn get(&self, suit: Suit, rank: Rank) -> &XObjectId {
        self.get_face(suit, rank, CardFace::Full)
    }

    /// Get the XObjectId for a specific rendition, falling back to the full
    /// card when that rendition was not registered.
    pub fn get_face(&self, suit: Suit, rank: Rank, face: CardFace) -> &XObjectId {
        let face = face.resolve(rank);
        self.cards
            .get(&(suit, rank, face))
            .or_else(|| self.cards.get(&(suit, rank, CardFace::Full)))
            .expect("requested card rendition should be loaded")
    }

    /// Get card dimensions in mm at a given scale factor
    pub fn card_size_mm(&self, scale: f32) -> (f32, f32) {
        (CARD_WIDTH_MM * scale, CARD_HEIGHT_MM * scale)
    }

    /// Create an XObjectTransform for placing a card at a given position and scale
    ///
    /// Position is the bottom-left corner of the card in mm
    pub fn transform_at(&self, x_mm: f32, y_mm: f32, scale: f32) -> XObjectTransform {
        self.transform_at_rotated(x_mm, y_mm, scale, 0.0)
    }

    /// Create an XObjectTransform for placing a card at a given position, scale, and rotation
    ///
    /// Position is the bottom-left corner of the card in mm.
    /// Rotation is in degrees, counter-clockwise around the card's bottom-left corner.
    pub fn transform_at_rotated(
        &self,
        x_mm: f32,
        y_mm: f32,
        scale: f32,
        rotate_degrees: f32,
    ) -> XObjectTransform {
        // Convert mm to points (1 mm = 2.834645669 pt)
        let mm_to_pt = 2.834_645_7;

        let rotate = if rotate_degrees.abs() < 0.001 {
            None
        } else {
            Some(printpdf::XObjectRotation {
                angle_ccw_degrees: rotate_degrees,
                rotation_center_x: Px(0),
                rotation_center_y: Px(0),
            })
        };

        XObjectTransform {
            translate_x: Some(Pt(x_mm * mm_to_pt)),
            translate_y: Some(Pt(y_mm * mm_to_pt)),
            scale_x: Some(scale),
            scale_y: Some(scale),
            rotate,
            dpi: Some(SVG_DPI),
        }
    }
}

/// Error type for card loading failures
#[derive(Debug)]
pub enum CardLoadError {
    MissingCard {
        suit: Suit,
        rank: Rank,
    },
    SvgParseError {
        suit: Suit,
        rank: Rank,
        message: String,
    },
}

impl std::fmt::Display for CardLoadError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CardLoadError::MissingCard { suit, rank } => {
                write!(f, "Missing card SVG: {} of {:?}", rank.to_char(), suit)
            }
            CardLoadError::SvgParseError {
                suit,
                rank,
                message,
            } => {
                write!(
                    f,
                    "Failed to parse SVG for {} of {:?}: {}",
                    rank.to_char(),
                    suit,
                    message
                )
            }
        }
    }
}

impl std::error::Error for CardLoadError {}

/// Embed the reduced (band, corner) pair for one court card.
macro_rules! court_pair {
    ($rank:literal, $suit:literal) => {
        (
            include_str!(concat!(
                "../../../assets/cards/variants/",
                $rank,
                "_of_",
                $suit,
                "_band.svg"
            )),
            include_str!(concat!(
                "../../../assets/cards/variants/",
                $rank,
                "_of_",
                $suit,
                "_corner.svg"
            )),
        )
    };
}

/// The (band, corner) variants for a court card, or None for a spot card.
///
/// Regenerate these assets with `python3 tools/make_card_variants.py` after
/// changing anything about how much of a covered card the layouts expose.
fn court_variants(suit: Suit, rank: Rank) -> Option<(&'static str, &'static str)> {
    Some(match (rank, suit) {
        (Rank::Jack, Suit::Clubs) => court_pair!("jack", "clubs"),
        (Rank::Jack, Suit::Diamonds) => court_pair!("jack", "diamonds"),
        (Rank::Jack, Suit::Hearts) => court_pair!("jack", "hearts"),
        (Rank::Jack, Suit::Spades) => court_pair!("jack", "spades"),
        (Rank::Queen, Suit::Clubs) => court_pair!("queen", "clubs"),
        (Rank::Queen, Suit::Diamonds) => court_pair!("queen", "diamonds"),
        (Rank::Queen, Suit::Hearts) => court_pair!("queen", "hearts"),
        (Rank::Queen, Suit::Spades) => court_pair!("queen", "spades"),
        (Rank::King, Suit::Clubs) => court_pair!("king", "clubs"),
        (Rank::King, Suit::Diamonds) => court_pair!("king", "diamonds"),
        (Rank::King, Suit::Hearts) => court_pair!("king", "hearts"),
        (Rank::King, Suit::Spades) => court_pair!("king", "spades"),
        _ => return None,
    })
}

/// Get the embedded SVG content for a specific card
fn get_card_svg(suit: Suit, rank: Rank) -> Result<&'static str, CardLoadError> {
    let svg = match (suit, rank) {
        // Spades
        (Suit::Spades, Rank::Ace) => include_str!("../../../assets/cards/ace_of_spades.svg"),
        (Suit::Spades, Rank::King) => include_str!("../../../assets/cards/king_of_spades.svg"),
        (Suit::Spades, Rank::Queen) => include_str!("../../../assets/cards/queen_of_spades.svg"),
        (Suit::Spades, Rank::Jack) => include_str!("../../../assets/cards/jack_of_spades.svg"),
        (Suit::Spades, Rank::Ten) => include_str!("../../../assets/cards/10_of_spades.svg"),
        (Suit::Spades, Rank::Nine) => include_str!("../../../assets/cards/9_of_spades.svg"),
        (Suit::Spades, Rank::Eight) => include_str!("../../../assets/cards/8_of_spades.svg"),
        (Suit::Spades, Rank::Seven) => include_str!("../../../assets/cards/7_of_spades.svg"),
        (Suit::Spades, Rank::Six) => include_str!("../../../assets/cards/6_of_spades.svg"),
        (Suit::Spades, Rank::Five) => include_str!("../../../assets/cards/5_of_spades.svg"),
        (Suit::Spades, Rank::Four) => include_str!("../../../assets/cards/4_of_spades.svg"),
        (Suit::Spades, Rank::Three) => include_str!("../../../assets/cards/3_of_spades.svg"),
        (Suit::Spades, Rank::Two) => include_str!("../../../assets/cards/2_of_spades.svg"),

        // Hearts
        (Suit::Hearts, Rank::Ace) => include_str!("../../../assets/cards/ace_of_hearts.svg"),
        (Suit::Hearts, Rank::King) => include_str!("../../../assets/cards/king_of_hearts.svg"),
        (Suit::Hearts, Rank::Queen) => include_str!("../../../assets/cards/queen_of_hearts.svg"),
        (Suit::Hearts, Rank::Jack) => include_str!("../../../assets/cards/jack_of_hearts.svg"),
        (Suit::Hearts, Rank::Ten) => include_str!("../../../assets/cards/10_of_hearts.svg"),
        (Suit::Hearts, Rank::Nine) => include_str!("../../../assets/cards/9_of_hearts.svg"),
        (Suit::Hearts, Rank::Eight) => include_str!("../../../assets/cards/8_of_hearts.svg"),
        (Suit::Hearts, Rank::Seven) => include_str!("../../../assets/cards/7_of_hearts.svg"),
        (Suit::Hearts, Rank::Six) => include_str!("../../../assets/cards/6_of_hearts.svg"),
        (Suit::Hearts, Rank::Five) => include_str!("../../../assets/cards/5_of_hearts.svg"),
        (Suit::Hearts, Rank::Four) => include_str!("../../../assets/cards/4_of_hearts.svg"),
        (Suit::Hearts, Rank::Three) => include_str!("../../../assets/cards/3_of_hearts.svg"),
        (Suit::Hearts, Rank::Two) => include_str!("../../../assets/cards/2_of_hearts.svg"),

        // Diamonds
        (Suit::Diamonds, Rank::Ace) => include_str!("../../../assets/cards/ace_of_diamonds.svg"),
        (Suit::Diamonds, Rank::King) => include_str!("../../../assets/cards/king_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Queen) => {
            include_str!("../../../assets/cards/queen_of_diamonds.svg")
        }
        (Suit::Diamonds, Rank::Jack) => include_str!("../../../assets/cards/jack_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Ten) => include_str!("../../../assets/cards/10_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Nine) => include_str!("../../../assets/cards/9_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Eight) => include_str!("../../../assets/cards/8_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Seven) => include_str!("../../../assets/cards/7_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Six) => include_str!("../../../assets/cards/6_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Five) => include_str!("../../../assets/cards/5_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Four) => include_str!("../../../assets/cards/4_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Three) => include_str!("../../../assets/cards/3_of_diamonds.svg"),
        (Suit::Diamonds, Rank::Two) => include_str!("../../../assets/cards/2_of_diamonds.svg"),

        // Clubs
        (Suit::Clubs, Rank::Ace) => include_str!("../../../assets/cards/ace_of_clubs.svg"),
        (Suit::Clubs, Rank::King) => include_str!("../../../assets/cards/king_of_clubs.svg"),
        (Suit::Clubs, Rank::Queen) => include_str!("../../../assets/cards/queen_of_clubs.svg"),
        (Suit::Clubs, Rank::Jack) => include_str!("../../../assets/cards/jack_of_clubs.svg"),
        (Suit::Clubs, Rank::Ten) => include_str!("../../../assets/cards/10_of_clubs.svg"),
        (Suit::Clubs, Rank::Nine) => include_str!("../../../assets/cards/9_of_clubs.svg"),
        (Suit::Clubs, Rank::Eight) => include_str!("../../../assets/cards/8_of_clubs.svg"),
        (Suit::Clubs, Rank::Seven) => include_str!("../../../assets/cards/7_of_clubs.svg"),
        (Suit::Clubs, Rank::Six) => include_str!("../../../assets/cards/6_of_clubs.svg"),
        (Suit::Clubs, Rank::Five) => include_str!("../../../assets/cards/5_of_clubs.svg"),
        (Suit::Clubs, Rank::Four) => include_str!("../../../assets/cards/4_of_clubs.svg"),
        (Suit::Clubs, Rank::Three) => include_str!("../../../assets/cards/3_of_clubs.svg"),
        (Suit::Clubs, Rank::Two) => include_str!("../../../assets/cards/2_of_clubs.svg"),
    };
    Ok(svg)
}
